#!/usr/bin/env python

YAGV_VERSION = "0.4"

import pyglet

# Disable error checking for increased performance
pyglet.options['debug_gl'] = False


from pyglet import clock
from pyglet.gl import *
from pyglet.graphics.shader import Shader, ShaderProgram
from pyglet.math import Vec3,Mat4
from pyglet.window import key
from pyglet.window import mouse

from gcodeParser import *
import os.path
import time

class App(object):
	def __init__(self):
		self.RX = 0.0
		self.RZ = 0.0
		self.zoom = 1.0
		
		# =========================
		# Shader
		# =========================

		vertex_source = """
		#version 330 core
		in vec3 position;
		in vec4 color;

		out vec4 v_color;

		uniform mat4 mvp;

		void main()
		{
			v_color = color;
			gl_Position = mvp * vec4(position, 1.0);
		}
		"""

		fragment_source = """
		#version 330 core
		in vec4 v_color;
		out vec4 fragColor;

		void main()
		{
			fragColor = vec4(v_color);
		}
		"""

		self.program = ShaderProgram(
			Shader(vertex_source, "vertex"),
			Shader(fragment_source, "fragment")
		)	
		
	
	def main(self):
		
		#### MAIN CODE ####
		print("Yet Another GCode Viewer v%s"%YAGV_VERSION)

		import sys
		if len(sys.argv) > 1:
			path = sys.argv[1]
		else:
			# get the real path to the script
			script_path = os.path.realpath(__file__)
			# get the containing folder
			script_dir = os.path.dirname(script_path)
			# default to hana
			path = os.path.join(script_dir, "data/hana_swimsuit_fv_solid_v1.gcode")
		
		self.load(path)
		
		# default to the middle layer
		self.layerIdx = int(len(self.model.layers) / 2)

		self.window = MyWindow(self, caption="Yet Another GCode Viewer v%s"%YAGV_VERSION, resizable=True)

		# debug: log all events
		# self.window.push_handlers(pyglet.window.event.WindowEventLogger())
		
		# generate graphics AFTER window generation
		self.generateGraphics()

		pyglet.app.run()

	def reload(self):
		self.load(self.path)
			
	def load(self, path):
		
		print("loading file %s ..."%repr(path))
		t1 = time.time()
		
		print()
		print("Parsing '%s'..."%path)
		print()
		
		self.path = path

		parser = GcodeParser()
		self.model = parser.parseFile(path)

		print()
		print("Done! %s"%self.model)
		print()
		
		# render the model
		print("rendering vertices...")
		self.renderVertices()
		print("rendering indexed colors...")
		self.renderIndexedColors()
		print("rendering true colors...")
		self.renderColors()
		print("generating graphics...")
		self.generateGraphics()
		print("Done")
		
		t2 = time.time()
		print("loaded file in %0.3f ms" % ((t2-t1)*1000.0, ))
	
	def renderVertices(self):
		t1 = time.time()
		
		self.vertices = []
		
		for layer in self.model.layers:
			
			layer_vertices = []
			
			x = layer.start["X"]
			y = layer.start["Y"]
			z = layer.start["Z"]
			for seg in layer.segments:
				layer_vertices.append(x)
				layer_vertices.append(y)
				layer_vertices.append(z)
				x = seg.coords["X"]
				y = seg.coords["Y"]
				z = seg.coords["Z"]
				layer_vertices.append(x)
				layer_vertices.append(y)
				layer_vertices.append(z)
				
			self.vertices.append(layer_vertices)
			
		t2 = time.time()
		print("end renderColors in %0.3f ms" % ((t2-t1)*1000.0, ))
	
	def renderIndexedColors(self):
		t1 = time.time()
		# pre-render segments to colors in the index
		styleToColoridx = {
			"extrude" : 0,
			"fly" : 1,
			"retract" : 2,
			"restore" : 3
			}
		
		# all the styles for all layers
		self.vertex_indexed_colors = []
		
		# for all layers
		for layer in self.model.layers:
			
			# index for this layer
			layer_vertex_indexed_colors = []
			for seg in layer.segments:
				# get color index for this segment
				styleCol = styleToColoridx[seg.style]
				# append color twice (once per end)
				layer_vertex_indexed_colors.extend((styleCol, styleCol))
			
			# append layer to all layers
			self.vertex_indexed_colors.append(layer_vertex_indexed_colors)
		t2 = time.time()
		print("end renderIndexedColors in %0.3f ms" % ((t2-t1)*1000.0, ))
	
	def renderColors(self):
		t1 = time.time()
		
		self.vertex_colors = [[],[],[]]
		
		# render color index to real colors
		colorMap = [
				# 0: old layer
				[[255,255,255, 40],[255,  0,  0, 20],[  0,  255,  0, 32],[  0,  0,  255, 32]], # extrude, fly, retract, restore
				# 1: current layer
				[[255,255,255,255],[255,  0,  0,128],[  0,  255,  0,128],[  0,  0,  255,128]], # extrude, fly, retract, restore
				# 2: limbo layer
				[[255,255,255, 10],[255,  0,  0, 10],[  0,  255,  0, 10],[  0,  0,  255, 10]] # extrude, fly, retract, restore
				]
		
		# for all 3 types
		for display_type in range(3):
			
			type_color_map = colorMap[display_type]
			
			# for all preindexed layer colors
			for indexes in self.vertex_indexed_colors:
				
				# render color indexes to colors
				colors = [type_color_map[e] for e in indexes]
				# flatten color values
				fcolors = []
				list(map(fcolors.extend, colors))
				
				# push colors to vertex list
				self.vertex_colors[display_type].append(fcolors)
				
		t2 = time.time()
		print("end renderColors in %0.3f ms" % ((t2-t1)*1000.0, ))
	
	def generateGraphics(self):
		t1 = time.time()
		
		self.graphics_old = []
		self.graphics_current = []
		self.graphics_limbo = []
		
		for layer_idx in range(len(self.vertices)):
			nb_layer_vertices = int(len(self.vertices[layer_idx])/3)
			vertex_list = self.program.vertex_list(nb_layer_vertices,
				GL_LINES,
				position = ('f', self.vertices[layer_idx]),
				color = ('Bn', self.vertex_colors[0][layer_idx])
			)
			self.graphics_old.append(vertex_list)
			
			vertex_list = self.program.vertex_list(nb_layer_vertices,
				GL_LINES,
				position = ('f', self.vertices[layer_idx]),
				color = ('Bn', self.vertex_colors[1][layer_idx])
			)
			self.graphics_current.append(vertex_list)
			
			vertex_list = self.program.vertex_list(nb_layer_vertices,
				GL_LINES,
				position = ('f', self.vertices[layer_idx]),
				color = ('Bn', self.vertex_colors[2][layer_idx])
			)
			self.graphics_limbo.append(vertex_list)
			#print(layer_idx, nb_layer_vertices, len(self.vertices[layer_idx]), len(self.vertex_colors[0][layer_idx]))


		
		t2 = time.time()
		print("end generateGraphics in %0.3f ms" % ((t2-t1)*1000.0, ))
		
		
	def rotate_drag_start(self, x, y, button, modifiers):
		self.rotateDragStartRX = self.RX
		self.rotateDragStartRZ = self.RZ
		self.rotateDragStartX = x
		self.rotateDragStartY = y


	def rotate_drag_do(self, x, y, dx, dy, buttons, modifiers):
		# deltas
		deltaX = x - self.rotateDragStartX
		deltaY = y - self.rotateDragStartY
		# rotate!
		self.RZ = self.rotateDragStartRZ + deltaX/5.0 # mouse X bound to model Z
		self.RX = self.rotateDragStartRX + deltaY/5.0 # mouse Y bound to model X


	def rotate_drag_end(self, x, y, button, modifiers):
		self.rotateDragStartRX = None
		self.rotateDragStartRZ = None
		self.rotateDragStartX = None
		self.rotateDragStartY = None


	def layer_drag_start(self, x, y, button, modifiers):
		self.layerDragStartLayer = self.layerIdx
		self.layerDragStartX = x
		self.layerDragStartY = y


	def layer_drag_do(self, x, y, dx, dy, buttons, modifiers):
		# sum x & y
		delta = x - self.layerDragStartX + y - self.layerDragStartY
		# new theoretical layer
		self.layerIdx = int(self.layerDragStartLayer + delta/5)
		# clamp layer to 0-max
		self.layerIdx = max(min(self.layerIdx, self.model.topLayer), 0)
		
		self.window.layerLabel.text = "layer %d"%self.layerIdx
		
	#	# clamp layer to 0-max, with origin slip
	#	if (self.layerIdx < 0):
	#		self.layerIdx = 0
	#		self.layerDragStartLayer = 0
	#		self.layerDragStartX = x
	#		self.layerDragStartY = y
	#	if (self.layerIdx > len(self.model.layers)-1):
	#		self.layerIdx = len(self.model.layers)-1
	#		self.layerDragStartLayer = len(self.model.layers)-1
	#		self.layerDragStartX = x
	#		self.layerDragStartY = y


	def layer_drag_end(self, x, y, button, modifiers):
		self.layerDragStartLayer = None
		self.layerDragStartX = None
		self.layerDragStartY = None


class MyWindow(pyglet.window.Window):

	# constructor
	def __init__(self, app, **kwargs):
		pyglet.window.Window.__init__(self, **kwargs)
		self.app = app
		self.hud()

		# Axes
		axes_pos = [
			0,0,0, self.app.model.bbox.xmax,0,0,
			0,0,0, 0,self.app.model.bbox.ymax,0,
			0,0,0, 0,0,self.app.model.bbox.zmax
		]

		axes_col = [
			1,0,0,1, 1,0,0,1,
			0,1,0,1, 0,1,0,1,
			0,0,1,1, 0,0,1,1
		]

		self.axes = self.app.program.vertex_list(
			6,
			GL_LINES,
			position=('f', axes_pos),
			color=('f', axes_col)
		)
		
		
		
		self.rotation_matrix = Mat4()  # Start als Identität
	
	# hud info
	def hud(self):
		
		# HUD labels
		self.blLabels = []
		self.brLabels = []
		self.tlLabels = []
		self.trLabels = []

		# help
		self.helpText = [
						"Ctrl-R to reload file",
						"Right-click & drag (any direction) to change layer",
						"Scroll to zoom",
						"Left-click & drag to rotate view"]
		for txt in self.helpText:
			self.blLabels.append(
				pyglet.text.Label(	txt,
									font_size=12) )

		# statistics
		## model stats
		self.statsLabel = pyglet.text.Label(	"",
										font_size=12,
										anchor_y='top')
		filename = os.path.basename(self.app.path)
		self.statsLabel.text = "%s: %d segments, %d layers."%(filename, len(self.app.model.segments), len(self.app.model.layers))
		
		## fps counter
		self.fpsLabel = pyglet.text.Label(	"",
										font_size=12,
										anchor_y='top')
		self.tlLabels.append(self.statsLabel)
		self.tlLabels.append(self.fpsLabel)

		# status
		## current Layer
		self.layerLabel = pyglet.text.Label(	"layer %d"%self.app.layerIdx,
										font_size=12,
										anchor_x='right', anchor_y='top')
		self.trLabels.append(self.layerLabel)

		# layout the labels in the window's corners
		self.placeLabels(self.width, self.height)
	
	
	# events
	def on_resize(self, width, height):
		glViewport(0, 0, width, height)
		self.placeLabels(width, height)
		#self.render(width, height)
		
		return pyglet.event.EVENT_HANDLED

	def on_mouse_press(self, x, y, button, modifiers):
		#print "on_mouse_press(x=%d, y=%d, button=%s, modifiers=%s)"%(x, y, button, modifiers)
		if button & mouse.LEFT:
			self.app.rotate_drag_start(x, y, button, modifiers)
			
		if button & mouse.RIGHT:
			self.app.layer_drag_start(x, y, button, modifiers)


	def on_mouse_drag(self, x, y, dx, dy, buttons, modifiers):
		#print "on_mouse_drag(x=%d, y=%d, dx=%d, dy=%d, buttons=%s, modifiers=%s)"%(x, y, dx, dy, buttons, modifiers)
		if buttons & mouse.LEFT:
			self.app.rotate_drag_do(x, y, dx, dy, buttons, modifiers)
			
		if buttons & mouse.RIGHT:
			self.app.layer_drag_do(x, y, dx, dy, buttons, modifiers)


	def on_mouse_release(self, x, y, button, modifiers):
		#print "on_mouse_release(x=%d, y=%d, button=%s, modifiers=%s)"%(x, y, button, modifiers)
		if button & mouse.LEFT:
			self.app.rotate_drag_end(x, y, button, modifiers)
			
		if button & mouse.RIGHT:
			self.app.layer_drag_end(x, y, button, modifiers)

	def on_key_release(self, symbol, modifiers):
		print("pressed key: %s, mod: %s"%(symbol, modifiers))
		#print "pressed key: %s, mod: %s"%(pyglet.window.key.R, pyglet.window.key.MOD_CTRL)
		if symbol==pyglet.window.key.R and modifiers & pyglet.window.key.MOD_CTRL:
			self.app.reload()
		
	def placeLabels(self, width, height):
		x = 5
		y = 5
		for label in self.blLabels:
			label.x = x
			label.y = y
			y += 20
			
		x = width - 5
		y = 5
		for label in self.brLabels:
			label.x = x
			label.y = y
			y += 20
			
		x = 5
		y = height - 5
		for label in self.tlLabels:
			label.x = x
			label.y = y
			y -= 20
			
		x = width - 5
		y = height - 5
		for label in self.trLabels:
			label.x = x
			label.y = y
			y -= 20


	def on_mouse_scroll(self, x, y, dx, dy):
		# zoom on mouse scroll
		delta = dx + dy
		if delta == 0:
			return
		z = 1.2 if delta>0 else 1/1.2
		self.app.zoom = max(1.0, self.app.zoom * z)
		#print 'mouse scroll:', `x, y, dx, dy`, `z, self.app.zoom`

	def on_draw(self):
		#print("draw")
		
		# Clear buffers
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
		
		projection = Mat4.perspective_projection(
			self.width / self.height, 
			fov = 65,
			z_near = 0.1, 
			z_far = 10000.0
		)

		# setup camera
		view = Mat4.look_at(Vec3(0,1.5,2),Vec3(0,0,0),Vec3(0,1,0))
		
		# enable alpha blending
		glEnable(GL_BLEND)
		glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
		
		# rotate axes to match reprap style
		reprap = Mat4.from_rotation(math.radians(-90), (1,0,0))
		# user rotate model
		rot_x = Mat4.from_rotation(math.radians(-self.app.RX), (1, 0, 0))  
		rot_z = Mat4.from_rotation(math.radians(self.app.RZ), (0,0,1))
		# fit & user zoom model
		max_width = max(
			self.app.model.bbox.dx(),
			self.app.model.bbox.dy(),
			self.app.model.bbox.dz()
		)
		scale = self.app.zoom / max_width
		scale = Mat4.from_scale((scale, scale, scale))
		trans = Mat4.from_translation((-self.app.model.bbox.cx(), -self.app.model.bbox.cy(), -self.app.model.bbox.cz()))
		model = reprap @ rot_x @ rot_z @ scale @ trans
		
		mvp = projection @ view @ model

		with self.app.program:
			self.app.program['mvp'] = mvp
			
			#draw axes
			glLineWidth(3)
			self.axes.draw(GL_LINES)

			glLineWidth(1)
			# Draw the model layers
			# lower layers
			for graphic in self.app.graphics_old[0:self.app.layerIdx]:
				graphic.draw(GL_LINES)
		
			glLineWidth(2)
			# highlighted layer
			graphic = self.app.graphics_current[self.app.layerIdx]
			graphic.draw(GL_LINES)
			
			glLineWidth(1)
			# limbo layers
			for graphic in self.app.graphics_limbo[self.app.layerIdx+1:]:
				graphic.draw(GL_LINES)
		
		
		# disable depth for HUD
		glDisable(GL_DEPTH_TEST)
		glDepthMask(0)
		
		#Set your camera up for 2d, draw 2d scene
		
		self.projection = Mat4.orthogonal_projection(0, self.width, 0, self.height, -1, 1)
		self.view = Mat4()
		
		self.fpsLabel.text = "%d fps"%int(round(pyglet.clock.get_frequency()))
		
		for label in self.blLabels:
			label.draw()
		for label in self.brLabels:
			label.draw()
		for label in self.tlLabels:
			label.draw()
		for label in self.trLabels:
			label.draw()
		
		# reenable depth for next model display
		glEnable(GL_DEPTH_TEST)
		glDepthMask(1)

App().main()
