#!/usr/bin/env python

YAGV_VERSION = "0.5.8"        # -- check Makefile and setup.py too

import sys
import pyglet
import math

# Disable error checking for increased performance
pyglet.options['debug_gl'] = False

from pyglet import clock
from pyglet.gl import *
from pyglet.graphics.shader import Shader, ShaderProgram
from pyglet.math import Vec3,Mat4
from pyglet.window import key
from pyglet.window import mouse

from gcodeParser import *
import os.path
import time

colorMap = {
	# Misc:
	"background": [ 1,1,1, 1. ],
	"grid": [ .2,.2,.2, 1. ],
	"text": [ 0,0,0, 1. ],

   # Gcode:
	"extrude": [ 0.,.8,0. ],
	"extrude_active": [ .8,0.,0. ],
	"extrude_wall": [ .2,.9,0. ],
	"extrude_wall_active": [ .8,.5,0. ],
	"extrude_support": [ .8,.8,0. ],
	"extrude_support_active": [ 1,.9,0. ],
	"retract": [ .8,.8,0. ],
	"unretract": [ .8,0.,.8 ],
	"motion": [ 0.,0.,1. ]
}

def preg_match(rex,s,m,opts={}):
	_m = re.search(rex,s)
	m.clear()
	if _m:
		m.append(s)
		m.extend(_m.groups())
		return True
	return False
                              
class App:
	def __init__(self):
		self.RX = 0.0
		self.RZ = 0.0
		self.PX = 0.0
		self.PY = 0.0
		self.zoom = 1.0
		self.conf = { }
		self.conf['bed_size'] = [ 200, 200 ]

		# =========================
		# Shader
		# =========================

		vertex_source = """
		#version 330 core
		in vec3 position;
		in vec4 color;

		out vec4 v_color;

		uniform mat4 mvp;

		void main()
		{
			v_color = color;
			gl_Position = mvp * vec4(position, 1.0);
		}
		"""

		fragment_source = """
		#version 330 core
		in vec4 v_color;
		out vec4 fragColor;

		void main()
		{
			fragColor = vec4(v_color);
		}
		"""

		self.program = ShaderProgram(
			Shader(vertex_source, "vertex"),
			Shader(fragment_source, "fragment")
		)
	
	def main(self):
		
		#### MAIN CODE ####

		path = ''

		i = 1
		while(i<len(sys.argv)):
			m = [ ]
			if preg_match('^--([\w\-]+)=(.*)$',sys.argv[i],m):
				m[1] = m[1].replace('-','_')
				self.conf[m[1]] = m[2]
			elif preg_match('^--([\w\-]+)$',sys.argv[i],m):
				m[1] = m[1].replace('-','_')
				self.conf[m[1]] = 1
			else:
		 		path = sys.argv[i]
			i += 1

		if 'help' in self.conf and self.conf['help']:
			print("""USAGE yagv %s: [<opts>] file.gcode
   options:
      --help               display this message
      --dark               enable dark mode
      --bed-size=<w>x<h>   set bed size (e.g. 200x240)
""" % YAGV_VERSION)
			sys.exit(0)
		if 'dark' in self.conf and self.conf['dark']:
			colorMap['background'] = [ 0,0,0, 1 ]
			colorMap['grid'] = [ 1,1,1, 0.1 ]
			colorMap['text'] = [ 1,1,1, 0.7 ]

		if type(self.conf['bed_size'])==str:
			self.conf['bed_size'] = list(map(lambda x: int(x),self.conf['bed_size'].split('x')))
			print(self.conf['bed_size'])

		if len(path)==0:
			script_path = os.path.realpath(__file__)
			script_dir = os.path.dirname(script_path)
			path = os.path.join(script_dir, "data/hana_swimsuit_fv_solid_v1.gcode")
			# WTF setuptools: no easy way to access EGG internal data file, we installed it in /usr/local/share/yagv/ instead :-(
			path = "/usr/local/share/yagv/data/hana_swimsuit_fv_solid_v1.gcode"

		print("Yet Another GCode Viewer v%s"%YAGV_VERSION)

		self.path = "loading ..."

		# -- create window soon, before loading ...
		self.window = MyWindow(self, caption="Yet Another GCode Viewer v%s: %s" % (YAGV_VERSION,os.path.basename(path)), resizable=True, width=1024, height=768)
		pyglet.gl.glClearColor(colorMap['background'][0],colorMap['background'][1],colorMap['background'][2],1)

		# debug: log all events
		# self.window.push_handlers(pyglet.window.event.WindowEventLogger())

		self.load(path)

		# default to the middle layer
		self.layerIdx = len(self.model.layers)//2
		self.window.hud()

		#img = pyglet.resource.image("icon.png")
		#img = pyglet.image.load("/usr/local/share/yagv/icon.png")
		#self.window.set_icon(img)

		pyglet.app.run()

	def reload(self):
		self.load(self.path)
			
	def load(self, path):
		
		print("loading file %s ..." % repr(path))
		t1 = time.time()
		
		print("Parsing '%s'..." % path)
		
		self.path = path

		parser = GcodeParser()
		self.model = parser.parseFile(path)

		print("Done! %s" % self.model)
		
		# render the model
		print("rendering vertices...")
		self.renderVertices()
		print("rendering indexed colors...")
		self.renderIndexedColors()
		print("rendering true colors...")
		self.renderColors()
		print("generating graphics...")
		self.generateGraphics()
		print("Done")
		
		t2 = time.time()
		print("loaded file in %0.3f ms" % ((t2-t1)*1000.0 ))

		self.generateAxes()
		self.generateGrid()
	
	def renderVertices(self):
		t1 = time.time()
		
		self.vertices = []

		for layer in self.model.layers:
			
			layer_vertices = []
			
			x = layer.start["X"]
			y = layer.start["Y"]
			z = layer.start["Z"]
			for seg in layer.segments:
				layer_vertices.append(x)
				layer_vertices.append(y)
				layer_vertices.append(z)
				x = seg.coords["X"]
				y = seg.coords["Y"]
				z = seg.coords["Z"]
				layer_vertices.append(x)
				layer_vertices.append(y)
				layer_vertices.append(z)

			self.vertices.append(layer_vertices)
			#layer.end['X'] = layer_vertices[:3]
			#layer.end['Y'] = layer_vertices[:2]
			#layer.end['Z'] = layer_vertices[:1]
			
		t2 = time.time()
		print("end renderColors in %0.3f ms" % ((t2-t1)*1000.0, ))
	
	def renderIndexedColors(self):
		t1 = time.time()
		# pre-render segments to colors in the index
		styleToColoridx = {
			"extrude" : 0,
			"fly" : 1,
			"retract" : 2,
			"restore" : 3,
	  		"extrude.wall": 4,
			"extrude.support": 5
			}
		
		# all the styles for all layers
		self.vertex_indexed_colors = []
		
		# for all layers
		for layer in self.model.layers:
			
			# index for this layer
			layer_vertex_indexed_colors = []
			for seg in layer.segments:
				# get color index for this segment
				if seg.style == 'extrude' and (seg.type == 'G1:wall' or seg.type == 'G1:shell' or seg.type == 'G1:perimeter' or seg.type.find('shell') or seg.type.find('shell')):
					styleCol = styleToColoridx['extrude.wall']
				elif seg.style == 'extrude' and seg.type == 'G1:support':
					styleCol = styleToColoridx['extrude.support']
				else:
					styleCol = styleToColoridx[seg.style]
				# append color twice (once per end)
				layer_vertex_indexed_colors.extend((styleCol, styleCol))
			
			# append layer to all layers
			self.vertex_indexed_colors.append(layer_vertex_indexed_colors)
		t2 = time.time()
		print("end renderIndexedColors in %0.3f ms" % ((t2-t1)*1000.0, ))
	
	def renderColors(self):
		t1 = time.time()
		
		self.vertex_colors = [[],[],[]]
		
		# render color index to real colors
		cm = [ 
			# 0: old layer
			[ colorMap['extrude'].copy(),        colorMap['motion'].copy(), colorMap['retract'].copy(), colorMap['unretract'].copy(), colorMap['extrude_wall'].copy(), colorMap['extrude_support'].copy() ],
			# 1: current layer
			[ colorMap['extrude_active'].copy(), colorMap['motion'].copy(), colorMap['retract'].copy(), colorMap['unretract'].copy(), colorMap['extrude_wall_active'].copy(), colorMap['extrude_support_active'].copy() ],
			# 2: limbo layer
			[ colorMap['extrude'].copy(),        colorMap['motion'].copy(), colorMap['retract'].copy(), colorMap['unretract'].copy(), colorMap['extrude_wall'].copy(), colorMap['extrude_support'].copy() ]
		]
		for i in range(6):         # -- add per type the alpha
			cm[0][i].append(.2 if i==1 or i==5 else .7)    # -- old
			cm[1][i].append(.2 if i==1 else 1.)    # -- current
			cm[2][i].append(.1)    # -- limbo
		
		# for all 3 types
		for display_type in range(3):
			
			#type_color_map = cm[display_type]

			# -- cumbersome float -> int color
			type_color_map = []
			n = 0
			for c in cm[display_type]:
				type_color_map.append([])
				for i in range(4):
					type_color_map[n].append(int(c[i]*255))
				n += 1

			# for all preindexed layer colors
			for indexes in self.vertex_indexed_colors:
				
				# render color indexes to colors
				colors = list(map(lambda e: type_color_map[e], indexes))
				# flatten color values
				fcolors = []
				list(map(fcolors.extend, colors))
				
				# push colors to vertex list
				self.vertex_colors[display_type].append(fcolors)
				
		t2 = time.time()
		print("end renderColors in %0.3f ms" % ((t2-t1)*1000.0, ))
	
	def generateGraphics(self):
		t1 = time.time()
		
		self.graphics_old = []
		self.graphics_current = []
		self.graphics_limbo = []
		
		for layer_idx in range(len(self.vertices)):
			nb_layer_vertices = int(len(self.vertices[layer_idx])/3)
			vertex_list = self.program.vertex_list(nb_layer_vertices,
				GL_LINES,
				position = ('f', self.vertices[layer_idx]),
				color = ('Bn', self.vertex_colors[0][layer_idx])
			)
			self.graphics_old.append(vertex_list)
			
			vertex_list = self.program.vertex_list(nb_layer_vertices,
				GL_LINES,
				position = ('f', self.vertices[layer_idx]),
				color = ('Bn', self.vertex_colors[1][layer_idx])
			)
			self.graphics_current.append(vertex_list)
			
			vertex_list = self.program.vertex_list(nb_layer_vertices,
				GL_LINES,
				position = ('f', self.vertices[layer_idx]),
				color = ('Bn', self.vertex_colors[2][layer_idx])
			)
			self.graphics_limbo.append(vertex_list)
			#print(layer_idx, nb_layer_vertices, len(self.vertices[layer_idx]), len(self.vertex_colors[0][layer_idx]))
		
		t2 = time.time()
		print("end generateGraphics in %0.3f ms" % ((t2-t1)*1000.0, ))

	def generateAxes(self):
		# Axes
		axes_pos = [
			0,0,0, self.model.bbox.xmax,0,0,
			0,0,0, 0,self.model.bbox.ymax,0,
			0,0,0, 0,0,self.model.bbox.zmax
		]

		axes_col = [
			1,0,0,1, 1,0,0,1,
			0,1,0,1, 0,1,0,1,
			0,0,1,1, 0,0,1,1
		]

		self.axes = self.program.vertex_list(
			6,
			GL_LINES,
			position=('f', axes_pos),
			color=('f', axes_col)
		)

	def generateGrid(self):
		count = 0
		grid_pos =[]
		grid_col = []
		sizex = self.conf['bed_size'][0]
		sizey = self.conf['bed_size'][1]
		for y in range(0,sizey+1):
			count += 2
			grid_pos.extend([0,y,0,  sizex,y,0])
			color = [colorMap['grid'][0],colorMap['grid'][1],colorMap['grid'][2],0.3 if y%10 == 0 else 0.1]
			grid_col.extend(color)
			grid_col.extend(color)
		for x in range(0,sizex+1):
			count += 2
			grid_pos.extend([x,0,0,  x,sizey,0])
			color = [colorMap['grid'][0],colorMap['grid'][1],colorMap['grid'][2],0.3 if x%10 == 0 else 0.1]
			grid_col.extend(color)
			grid_col.extend(color)

		self.grid = self.program.vertex_list(
			count,
			GL_LINES,
			position=('f', grid_pos),
			color=('f', grid_col)
		)

	# -- rotate		
	def rotate_drag_start(self, x, y, button, modifiers):
		self.rotateDragStartRX = self.RX
		self.rotateDragStartRZ = self.RZ
		self.rotateDragStartX = x
		self.rotateDragStartY = y

	def rotate_drag_do(self, x, y, dx, dy, buttons, modifiers):
		# deltas
		deltaX = x - self.rotateDragStartX
		deltaY = y - self.rotateDragStartY
		# rotate!
		self.RZ = self.rotateDragStartRZ + deltaX/5.0 # mouse X bound to model Z
		self.RX = self.rotateDragStartRX + deltaY/5.0 # mouse Y bound to model X

	def rotate_drag_end(self, x, y, button, modifiers):
		self.rotateDragStartRX = None
		self.rotateDragStartRZ = None
		self.rotateDragStartX = None
		self.rotateDragStartY = None

	def layer_drag_start(self, x, y, button, modifiers):
		self.layerDragStartLayer = self.layerIdx
		self.layerDragStartX = x
		self.layerDragStartY = y

	def layer_drag_do(self, x, y, dx, dy, buttons, modifiers):
		# sum x & y
		delta = x - self.layerDragStartX + y - self.layerDragStartY
		# new theoretical layer
		self.layerIdx = int(self.layerDragStartLayer + delta//5)
		# clamp layer to 0-max
		self.layerIdx = max(min(self.layerIdx, self.model.topLayer), 0)
		self.layer_update()
		
	#	# clamp layer to 0-max, with origin slip
	#	if (self.layerIdx < 0):
	#		self.layerIdx = 0
	#		self.layerDragStartLayer = 0
	#		self.layerDragStartX = x
	#		self.layerDragStartY = y
	#	if (self.layerIdx > len(self.model.layers)-1):
	#		self.layerIdx = len(self.model.layers)-1
	#		self.layerDragStartLayer = len(self.model.layers)-1
	#		self.layerDragStartX = x
	#		self.layerDragStartY = y

	# -- layer select		
	def layer_update(self):
		#self.window.layerLabel.text = "layer %d (z=%.2f)" % (self.layerIdx,self.model.layers[self.layerIdx].start['Z'])
		if self.model.layers[self.layerIdx].bbox.zmin != self.model.layers[self.layerIdx].bbox.zmax:
			self.window.layerLabel.text = "layer %d (z=%.2f..%.2f)" % (self.layerIdx,self.model.layers[self.layerIdx].bbox.zmin,self.model.layers[self.layerIdx].bbox.zmax)
		else:
			self.window.layerLabel.text = "layer %d (z=%.2f)" % (self.layerIdx,self.model.layers[self.layerIdx].start['Z'])
		#print(self.model.layers[self.layerIdx].bbox.zmin)

	def layer_up(self):
		self.layerIdx = max(min(self.layerIdx+1, self.model.topLayer), 0)
		self.layer_update()

	def layer_down(self):
		self.layerIdx = max(min(self.layerIdx-1, self.model.topLayer), 0)
		self.layer_update()

	def layer_bottom(self):
		self.layerIdx = min(1, self.model.topLayer)
		self.layer_update()

	def layer_top(self):
		self.layerIdx = self.model.topLayer
		self.layer_update()

	def layer_drag_end(self, x, y, button, modifiers):
		self.layerDragStartLayer = None
		self.layerDragStartX = None
		self.layerDragStartY = None

	# -- panning
	def panning_start(self, x, y, button, modifiers):
		self.panningStartPX = self.PX
		self.panningStartPY = self.PY
		self.panningStartX = x
		self.panningStartY = y

	def panning_do(self, x, y, dx, dy, buttons, modifiers):
		# deltas
		#deltaX = x - self.panningStartX
		#deltaY = y - self.panningStartY
		# -- panning done with proper rotation
		deltaX = math.cos(-self.RZ/180*math.pi) * (x - self.panningStartX) + math.sin(self.RZ/180*math.pi) * (y - self.panningStartY)
		deltaY = math.sin(-self.RZ/180*math.pi) * (x - self.panningStartX) + math.cos(self.RZ/180*math.pi) * (y - self.panningStartY)
		# pan!
		f = 5
		self.PX = self.panningStartPX + deltaX/f # mouse X bound to model X
		self.PY = self.panningStartPY + deltaY/f # mouse Y bound to model Y

	def panning_end(self, x, y, button, modifiers):
		self.panningStartX = None
		self.panningStartY = None


def glLine(p1,p2,c):
	glBegin(GL_LINES)
	glColor4f(c[0],c[1],c[2],c[3])
	glVertex3f(p1[0],p1[1],p1[2])
	glVertex3f(p2[0],p2[1],p2[2])
	glEnd()
	
class MyWindow(pyglet.window.Window):

	# constructor
	def __init__(self, app, **kwargs):
		pyglet.window.Window.__init__(self, **kwargs)
		self.app = app
		#self.hud()
	
	# hud info
	def hud(self):
		
		# HUD labels
		self.blLabels = []
		self.brLabels = []
		self.tlLabels = []
		self.trLabels = []

		c_texti = list(map(lambda x: int(x*255), colorMap['text']))
		#self.brLabels.append(pyglet.text.Label("yagv "+YAGV_VERSION,font_size=10,color=c_texti,anchor_x='right', anchor_y='bottom'))
      
		# help
		self.helpText = [
						"Left-mouse: rotate | Middle: change layer, Scroll: zoom | Right: panning   Ctrl-R: reload"]
		for txt in self.helpText:
			self.blLabels.append(
				pyglet.text.Label(	txt,
									font_size=10,color=c_texti) )

		# statistics
		## model stats
		self.statsLabel = pyglet.text.Label(	"",
										font_size=10,color=c_texti,
										anchor_y='top')
		filename = os.path.basename(self.app.path)
		self.statsLabel.text = "%s: %d layers (%d segments), %.1fm filament" % (filename, len(self.app.model.layers), len(self.app.model.segments), self.app.model.extrudate/1000.0)
		
		## fps counter
		self.fpsLabel = pyglet.text.Label(	"",
										font_size=10,color=c_texti,
										anchor_y='top')
		self.tlLabels.append(self.statsLabel)
		#self.tlLabels.append(self.fpsLabel)

		# status
		## current Layer
		self.layerLabel = pyglet.text.Label(	"layer %d (z=%.2f)" % (
			self.app.layerIdx,
			self.app.model.layers[self.app.layerIdx].start['Z'],
			#self.app.model.layers[self.app.layerIdx].end['Z']
			#self.app.model.layers[self.app.layerIdx].bbox.zmin,
			#self.app.model.layers[self.app.layerIdx].bbox.zmax
			), font_size=10,color=c_texti,anchor_x='right', anchor_y='top')
		self.trLabels.append(self.layerLabel)

		# layout the labels in the window's corners
		self.placeLabels(self.width, self.height)
	
	
	# events
	def on_resize(self, width, height):
		glViewport(0, 0, width, height)
		self.placeLabels(width, height)
		#self.render(width, height)
		
		return pyglet.event.EVENT_HANDLED

	def on_mouse_press(self, x, y, button, modifiers):
		#print("on_mouse_press(x=%d, y=%d, button=%s, modifiers=%s)"%(x, y, button, modifiers))
		if button & mouse.LEFT:
			self.app.rotate_drag_start(x, y, button, modifiers)
			
		if button & mouse.MIDDLE:
			self.app.layer_drag_start(x, y, button, modifiers)

		if button & mouse.RIGHT:
			self.app.panning_start(x, y, button, modifiers)


	def on_mouse_drag(self, x, y, dx, dy, buttons, modifiers):
		#print("on_mouse_drag(x=%d, y=%d, dx=%d, dy=%d, buttons=%s, modifiers=%s)"%(x, y, dx, dy, buttons, modifiers))
		if buttons & mouse.LEFT:
			self.app.rotate_drag_do(x, y, dx, dy, buttons, modifiers)
			
		if buttons & mouse.MIDDLE:
			self.app.layer_drag_do(x, y, dx, dy, buttons, modifiers)

		if buttons & mouse.RIGHT:
			self.app.panning_do(x, y, dx, dy, buttons, modifiers)


	def on_mouse_release(self, x, y, button, modifiers):
		#print("on_mouse_release(x=%d, y=%d, button=%s, modifiers=%s)"%(x, y, button, modifiers))
		if button & mouse.LEFT:
			self.app.rotate_drag_end(x, y, button, modifiers)
			
		if button & mouse.MIDDLE:
			self.app.layer_drag_end(x, y, button, modifiers)

		if button & mouse.RIGHT:
			self.app.panning_end(x, y, button, modifiers)

	def on_text_motion(self, motion):
		if motion==pyglet.window.key.MOTION_DOWN:
			self.app.layer_down()
		elif motion==pyglet.window.key.MOTION_UP:
			self.app.layer_up()

	def on_key_press(self, symbol, modifiers):
		print("pressed key: %s, mod: %s"%(symbol, modifiers))

		if symbol==pyglet.window.key.R and modifiers & pyglet.window.key.MOD_CTRL:
			self.app.reload()
		elif symbol==pyglet.window.key.HOME:
			self.app.layer_bottom()
		elif symbol==pyglet.window.key.END:
			self.app.layer_top()
		elif symbol==pyglet.window.key.Q:
			pyglet.app.exit()
		
	def placeLabels(self, width, height):
		x = 5
		y = 5
		for label in self.blLabels:
			label.x = x
			label.y = y
			y += 20
			
		x = width - 5
		y = 5
		for label in self.brLabels:
			label.x = x
			label.y = y
			y += 20
			
		x = 5
		y = height - 5
		for label in self.tlLabels:
			label.x = x
			label.y = y
			y -= 20
			
		x = width - 5
		y = height - 5
		for label in self.trLabels:
			label.x = x
			label.y = y
			y -= 20


	def on_mouse_scroll(self, x, y, dx, dy):
		# zoom on mouse scroll
		delta = dx + dy
		if delta == 0:
			return
		z = 1.2 if delta>0 else 1/1.2
		self.app.zoom = max(1.0, self.app.zoom * z)
		#print('mouse scroll:', `x, y, dx, dy`, `z, self.app.zoom`)

	def on_draw(self):
		#print("draw")
		
		# Clear buffers
		glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
		
		# setup projection
		projection = Mat4.perspective_projection(
			self.width / self.height, 
			fov = 65,
			z_near = 0.1, 
			z_far = 10000.0
		)

		# setup camera
		view = Mat4.look_at(Vec3(0,1.5,2),Vec3(0,0,0),Vec3(0,1,0))
		
		# enable alpha blending
		glEnable(GL_BLEND)
		glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
		
		# rotate axes to match reprap style
		reprap = Mat4.from_rotation(math.radians(-90), (1,0,0))
		# user rotate model
		rot_x = Mat4.from_rotation(math.radians(-self.app.RX), (1, 0, 0))  
		rot_z = Mat4.from_rotation(math.radians(self.app.RZ), (0,0,1))
		# fit & user zoom model
		max_width = max(
			self.app.model.bbox.dx(),
			self.app.model.bbox.dy(),
			self.app.model.bbox.dz()
		)
		scale = self.app.zoom / max_width
		scale = Mat4.from_scale((scale, scale, scale))
		pan = Mat4.from_translation((self.app.PX, self.app.PY,0))
		trans = Mat4.from_translation((-self.app.model.bbox.cx(), -self.app.model.bbox.cy(), -self.app.model.bbox.cz()))
		model = reprap @ rot_x @ rot_z @ scale @ pan @ trans
		
		mvp = projection @ view @ model

		with self.app.program:
			self.app.program['mvp'] = mvp
			
			#draw axes
			glLineWidth(3)
			self.app.axes.draw(GL_LINES)

			# draw bed grid
			glLineWidth(1)
			self.app.grid.draw(GL_LINES)

			# -- draw the model layers
			#    lower layers
			glLineWidth(1)
			for graphic in self.app.graphics_old[0:self.app.layerIdx]:
				graphic.draw(GL_LINES)
		
			#    highlighted layer
			glLineWidth(2)
			graphic = self.app.graphics_current[self.app.layerIdx]
			graphic.draw(GL_LINES)
		
			#    limbo layers
			glLineWidth(1)
			for graphic in self.app.graphics_limbo[self.app.layerIdx+1:]:
				graphic.draw(GL_LINES)
		
		# disable depth for HUD
		glDisable(GL_DEPTH_TEST)
		glDepthMask(0)
		
		# Set your camera up for 2d, draw 2d scene
		
		self.projection = Mat4.orthogonal_projection(0, self.width, 0, self.height, -1, 1)
		self.view = Mat4()
		
		self.fpsLabel.text = "%d fps"%int(round(pyglet.clock.get_frequency()))
		
		for label in self.blLabels:
			label.draw()
		for label in self.brLabels:
			label.draw()
		for label in self.tlLabels:
			label.draw()
		for label in self.trLabels:
			label.draw()
		
		# reenable depth for next model display
		glEnable(GL_DEPTH_TEST)
		glDepthMask(1)

App().main()
